# Generated by Django 4.2.5 on 2023-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar', '0003_securityaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=12)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Clave', models.CharField(max_length=128)),
                ('NumeroCuenta', models.CharField(max_length=20)),
                ('SaldoContable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SaldoCuentaCorriente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SaldoLineaCredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalCargos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalAbonos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.BooleanField(default=True)),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
