# Generated by Django 4.2.5 on 2023-09-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar', '0004_nuevoregistro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevoregistro',
            old_name='Rut',
            new_name='rut',
        ),
    ]
