# Generated by Django 4.2.5 on 2023-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar', '0006_nuevoregistro_groups_nuevoregistro_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='password',
        ),
        migrations.RemoveField(
            model_name='nuevoregistro',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='nuevoregistro',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
