# Generated by Django 4.2.5 on 2023-09-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar', '0008_alter_nuevoregistro_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevoregistro',
            name='NumeroCuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nuevoregistro',
            name='SaldoContable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nuevoregistro',
            name='SaldoCuentaCorriente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nuevoregistro',
            name='SaldoLineaCredito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nuevoregistro',
            name='TotalAbonos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nuevoregistro',
            name='TotalCargos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
