# Generated by Django 4.2.5 on 2023-11-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0002_alter_transferencia_cuenta_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='detalles',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
